accounts/urls.py
from . import views
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import login, logout
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from accounts.views import (
    logout_view,
    register,
    edit_profile,
    ProfileView,
    ProfileOverview,
    deposit_view,
    withdraw_view,
    transaction_history_view,

)


app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name= 'accounts/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name= 'accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^overview/$', ProfileOverview.as_view(), name='overview_profile'),
    url(r'^profile/$', ProfileView.as_view(), name='view_profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name= 'accounts/reset_password.html',
                        email_template_name='accounts/reset_password_email.html',
                        success_url=reverse_lazy('accounts:password_reset_done')), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'),
                                                                 name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,23})/$',
                                    PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html',
                                    success_url=reverse_lazy('accounts:password_reset_complete')),
                                    name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),
                                                                        name='password_reset_complete'),
    url(r'^withdraw/$', views.withdraw_view, name='withdraw'),
    url(r'^deposit/$', views.deposit_view, name='deposit'),
    url(r'^history/$', views.transaction_history_view, name='transaction_history')

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from decimal import Decimal
from django.core.validators import MinValueValidator


CHOISE_LOCATIONS = (('CLUJ','Cluj'),('MARAMURES','Maramures'),
                    ('ALBA', 'Alba'), ('ILFOV', 'Ilfov'),
                    ('IASI', 'Iasi'), ('TIMIS', 'Timis'),
                    ('BIHOR', 'Bihor'))


class UserProfile(AbstractUser):
    card_nr = models.CharField(max_length=16, default='')
    location = models.CharField(choices=CHOISE_LOCATIONS, max_length=20, default='')
    phone_number = models.CharField(_('phone number'), max_length=10, default='')
    bank_account = models.CharField(_('bank account'), max_length=20, default='')
    account_balance = models.IntegerField(_('account balance'), default=0)
    profile_pic = models.ImageField(upload_to='profile_image', null=True, blank=True)

    def __str__(self):
        return self.username

    @property
    def profile_pic_url(self):
        if self.profile_pic:
            return self.profile_pic.url
        return '/media/profile_image/no_img.jpg'


class Deposit(models.Model):
    user = models.ForeignKey(UserProfile, on_delete='CASCADE')
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('1.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)


class Withdraw(models.Model):
    user = models.ForeignKey(UserProfile, on_delete='CASCADE')
    amount = models.DecimalField(
        decimal_places=2,
        max_digits=12,
        validators=[
            MinValueValidator(Decimal('1.00'))
        ]
    )
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user)

accounts/forms.py
from django import forms
from django.contrib.auth import password_validation, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from .models import UserProfile, Deposit, Withdraw
from django.utils.translation import gettext, gettext_lazy as _
from .validators import UnicodeUsernameValidator
from django.core.validators import RegexValidator


User = get_user_model()


CHOISE_LOCATIONS = (('CLUJ', 'Cluj'), ('MARAMURES', 'Maramures'),
                    ('ALBA', 'Alba'), ('ILFOV', 'Ilfov'),
                    ('IASI', 'Iasi'), ('TIMIS', 'Timis'),
                    ('BIHOR', 'Bihor'))


class RegistrationForm(UserCreationForm):

    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
        'username_used':_("Username is already in use."),}

    username_validator = UnicodeUsernameValidator()
    username     = forms.CharField(max_length=20,
        help_text=_('Required. 20 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },)
    email        = forms.EmailField(required=True)
    password1    = forms.CharField(max_length=100, widget=forms.PasswordInput, label= ("Password"))
    password2    = forms.CharField(max_length=100, widget=forms.PasswordInput, label= ("Password Confirmation"))

    class Meta:
        model = User
        fields = [
            'username',
            'email',
            'password1',
            'password2',
                ]

    #
    def clean_email(self):
        email = self.cleaned_data['email']
        if email and User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email already exists')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch'
            )
        return password2

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class EditProfileForm(forms.ModelForm):

    first_name = forms.CharField(widget=forms.TextInput(attrs={'pattern': r'^[A-Za-z]+$'}), max_length=20, required=True)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'pattern': r'^[A-Za-z]+$'}), max_length=20, required=True)
    email = forms.EmailField(required=True)
    card_nr = forms.CharField(widget=forms.TextInput(attrs={'pattern': r'^[0-9]+$'}),
                              min_length=16, max_length=16, required=True)
    location = forms.ChoiceField(choices=CHOISE_LOCATIONS, required=True)
    phone_number = forms.CharField(widget=forms.TextInput(attrs={'pattern': r'^[0-9]+$'}),
                                   min_length=10, max_length=10, required=True)
    profile_pic = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = [
            'first_name',
            'last_name',
            'email',
            'card_nr',
            'location',
            'phone_number',
            'profile_pic'
        ]


class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ["amount"]


class WithdrawForm(forms.ModelForm):
    class Meta:
        model = Withdraw
        fields = ["amount"]

accounts/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import UserProfile, Deposit, Withdraw
from accounts.forms import (
    RegistrationForm,
    EditProfileForm,
    DepositForm,
    WithdrawForm,

)

from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from .forms import RegistrationForm
from django.urls import reverse
from django.views.generic import TemplateView
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def transaction_history_view(request):
    deposits = Deposit.objects.filter(user=request.user)
    withdraws = Withdraw.objects.filter(user=request.user)

    deposits_history = [
        {"timestamp": entry.timestamp, "amount": entry.amount, "type": "Deposit"}
        for entry in deposits
    ]
    withdraws_history = [
        {"timestamp": entry.timestamp, "amount": -entry.amount, "type":"Withdraw"}
        for entry in withdraws
    ]

    all_history = sorted(deposits_history + withdraws_history, key=lambda x: x["timestamp"])

    args = {'user': request.user,
            'deposit': deposits,
            "withdraw": withdraws,
            "all_history": all_history
            }
    return render(request, "accounts/transactions_history.html", args)


class ProfileOverview(TemplateView):
        template_name = 'accounts/overview.html'

        def get(self, request):
            users = UserProfile.objects.filter(username=request.user.username).values()

            args = {'users': users}
            return render(request, self.template_name, args)


class ProfileView(TemplateView):
        template_name = 'accounts/profile.html'

        def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context['profile_image'] = self.request.user.profile_pic_url
            context['user'] = self.request.user
            return context


def withdraw_view(request):
        form = WithdrawForm(request.POST or None)

        if form.is_valid():
            withdraw = form.save(commit=False)
            withdraw.user = request.user

            # checks if user is trying to Withdraw more than his balance.
            if withdraw.user.account_balance >= withdraw.amount:
                # substracts users withdrawal from balance
                withdraw.user.account_balance -= withdraw.amount
                withdraw.user.save()
                withdraw.save()
                return HttpResponseRedirect(reverse('accounts:overview_profile'))

            else:
                messages.error(
                    request,
                    'You Can Not Withdraw More Than You Balance.'
                    )

        args = {"form": form}
        return render(request, "accounts/withdraw.html", args)


def deposit_view(request):
    form = DepositForm(request.POST or None)

    if form.is_valid():
        deposit = form.save(commit=False)
        deposit.user = request.user
        # adds users deposit to balance.
        deposit.user.account_balance += deposit.amount
        deposit.user.save()
        deposit.save()
        return HttpResponseRedirect(reverse('accounts:overview_profile'))

    args = {"form": form}
    return render(request, "accounts/deposit.html", args)


def logout_view(request):
    return render(request, 'accounts/logout.html')


def register(request, *args, **kwargs):
    form = RegistrationForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    # else:
    #     form = RegistrationForm()
    context = {'form': form}
    return render(request, 'accounts/reg_form.html', context)


@login_required()
def edit_profile(request):
    user = request.user
    form = EditProfileForm(request.POST or None, request.FILES, instance=user)
    if request.method == 'POST':
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            email = form.cleaned_data['email']
            phone_number = form.cleaned_data['phone_number']
            location = form.cleaned_data['location']
            card_nr = form.cleaned_data['card_nr']
            profile_pic = form.cleaned_data['profile_pic']
            #BANK ACCOUNT CREATION
            bank_id = 'RO' + (str(ord(first_name[0])) + str(ord(first_name[-1])))[-2:] + \
                            'BANK' + (str(ord(first_name[0])) + str(ord(first_name[-1])))[:3] + \
                            (str(ord(last_name[0])) + str(ord(last_name[-1])))[:3] + (card_nr[:3]) + (card_nr[-3:])
            #-------------------------

            user.bank_account = bank_id
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.email = request.POST['email']
            user.phone_number = request.POST['phone_number']
            user.location = request.POST['location']
            user.card_nr = request.POST['card_nr']
            user.profile_pic = request.FILES['profile_pic'] if 'profile_pic' in request.FILES else user.profile_pic
            user.save()
            args = {'form': form, 'username': user.username}
            return HttpResponseRedirect(reverse('accounts:view_profile'), args)

    else:
        first_name = user.first_name
        last_name = user.last_name
        email = user.email
        phone_number = user.phone_number
        location = user.location
        card_nr = user.card_nr
        profile_pic = user.profile_pic
        form = EditProfileForm(initial={'first_name':first_name, 'last_name':last_name, 'email':email,
                                        'phone_number':phone_number, 'location':location, 'card_nr':card_nr,
                                        'profile_pic': profile_pic})
        args = {'form':form, 'username':user.username}
        return render(request, 'accounts/edit_profile.html', args)


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponseRedirect(reverse('accounts:view_profile'))
        else:
            args = {'form': form}
            return render(request, 'accounts/change_password.html', args)
    else:
        form = PasswordChangeForm(user=request.user)

        args = {'form':form}
        return render(request, 'accounts/change_password.html', args)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
<title>Change password</title>
{% endblock %}

{% block body %}
<div class="container">
    <br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
</div>
{% endblock %}

accounts/templates/accounts/deposit.html
{% extends 'base.html' %}

{% block head %}
<title>Deposit</title>
{% endblock %}

{% block body %}
<div class="container">
    <br>
    <br>

<form method="POST" action="{% url 'accounts:deposit' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="DEPOSIT"/>
</form>

</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
<title>Login</title>
{% endblock %}

{% block body %}
<div class="container">
<br>
    <H1> Welcome !</H1>
    <p> You can log in here !</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
<title>Logout</title>
{% endblock %}

{% block body %}

<div class="cointainer">
  <h1>You have logged out.</h1>
</div>

{% endblock %}

accounts/templates/accounts/overview.html
{% extends 'base.html' %}

{% block head %}
<title>Account overview</title>
{% endblock %}

{% block body %}
<div class="container">
    <br>
        <p>
            <html>
            <head>
                <style>
table {
    border-collapse: collapse;
    width: 50%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
            </head>
            <body>
            <table>
                <tr>
                    <h3>MY ACCOUNT</h3>
                </tr>
                <tr>

                    <td> {{ user.first_name }} {{ user.last_name }}</td>
                    <td> {{ user.bank_account }}</td>
                    <td> {{ user.account_balance }} $</td>

                </tr>
            </table>
            <br>
            <tr><a href="{% url 'accounts:withdraw' %}"><button type="button">Make a withdraw</button></a></tr>
            <tr><a href="{% url 'accounts:deposit' %}"><button type="button">Make a deposit</button></a></tr><br><br>
            <tr><a href="{% url 'accounts:transaction_history' %}"><button type="button">Transactions History</button></a></tr>
            </body>
            </html>
        </p>

</div>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
<title>Profile</title>
{% endblock %}

{% block body %}
<div class="container">
    <br>
        <p>
            <html>
            <head>
                <style>
table {
    border-collapse: collapse;
    width: 50%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>
            </head>
            <body>
            <table>

                <tr>
                    <tr><h3><img src="{{ profile_image }}" width="100" height="100"> {{ user.username }}</h3></tr>
                    <td> First name:</td> <td>{{ user.first_name }}</td><tr>
                    <td> Last name: </td> <td>{{ user.last_name}}</td><tr>
                    <td>Card number:</td> <td>{{ user.card_nr }}</td><tr>
                    <td>Email:</td> <td>{{ user.email }}</td><tr>
                    <td>Location:</td> <td>{{ user.location }}</td><tr>
                    <td>Phone number: </td> <td>{{ user.phone_number }}</td>

                    {% if user.is_superuser %}
                     <p>*Admin</p>
                    {% elif user.is_staff %}
                    <p>*Staff</p>
                    {% endif %}
                </tr>
            </table>
            </body>
            </html>
        </p>
</div>
{% endblock %}

accounts/templates/accounts/reg_form.html
{% extends 'base.html' %}

{% block head %}
<title>Registration</title>
{% endblock %}

{% block body %}
<div class="container">
    <br>
    <br>
    <br>
    <br>
    <h1> Register here: </h1>
    <br>
<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Register"/>
</form>

</div>

{% endblock %}

accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
{% endblock %}

{% block body %}
<div class="container">
<br>
    <H1> Password reset</H1>
    <p> Forgotten your password? Enter your email address below,
        and we'll email instructions for setting a new one.</p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
{% endblock %}

{% block body %}
<div class="container">
<br>
    <H1> Password reset complete</H1>
    <br>

    <a href="{% url 'accounts:login' %}">Login</a>

</div>


{% endblock %}

accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
{% endblock %}

{% block body %}
<div class="container">
<br>
    <H1> Enter new password</H1>
    <br>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Reset password</button>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
<title>Reset password</title>
{% endblock %}

{% block body %}
<div class="container">
<br>
    <H1> Password reset sent</H1>
    <p> We've emailed you instructions for setting your password, if an account exists with the email you
        entered. You should receive them shortly.
        If you don't receive an email, please make sure you've entered the address you registered with,
        and check your spam folder.</p>

</div>


{% endblock %}

accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

accounts/templates/accounts/transactions_history.html
{% extends 'base.html' %}

{% block head %}
<title>Transactions History</title>
{% endblock %}

{% block body %}

<div class="container">
    <br>
    <h2><b>Transaction history</b></h2>
    <br>

    <table class="table table-hover table-bordered">
        <thead>
        <tr>
            <th width="10">#</th>
            <th width="30">Date/Time</th>
            <th>Details</th>
            <th>Amount ($)</th>
        </tr>
        </thead>
        <tbody>
        <tr>
    {% for entry in all_history %}
            <th scope="row">{{forloop.counter}}</th>
            <td>{{entry.timestamp}}</td>
            <td>{{entry.type}}</td>
            <td>{{entry.amount}}</td>
        </tr>
    {% endfor %}
    {% endblock %}

accounts/templates/accounts/withdraw.html
{% extends 'base.html' %}

{% block head %}
<title>Withdraw</title>
{% endblock %}

{% block body %}
{% include 'messages.html' %}
<div class="container">
    <br>
    <br>
<div class="alert alert-info" role="alert"><h4>Your Current Account Balance is {{ user.account_balance }} $</h4></div>

<form method="POST" action="{% url 'accounts:withdraw' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="WITHDRAW"/>
</form>


{% endblock %}