accounts/urls.py
from . import views
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib import admin
from django.contrib.auth import login, logout
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from django.urls import path
from accounts.views import (
    logout_view,
    register,
    edit_profile,
    ProfileView,
    ProfileOverview,
    deposit_view,
    withdraw_view,
    transaction_history_view,

)


app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name= 'accounts/login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(template_name= 'accounts/logout.html'), name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^overview/$', ProfileOverview.as_view(), name='overview_profile'),
    url(r'^profile/$', ProfileView.as_view(), name='view_profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView.as_view(template_name= 'accounts/reset_password.html',
                        email_template_name='accounts/reset_password_email.html',
                        success_url=reverse_lazy('accounts:password_reset_done')), name='reset_password'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'),
                                                                 name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,23})/$',
                                    PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html',
                                    success_url=reverse_lazy('accounts:password_reset_complete')),
                                    name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'),
                                                                        name='password_reset_complete'),
    url(r'^withdraw/$', views.withdraw_view, name='withdraw'),
    url(r'^deposit/$', views.deposit_view, name='deposit'),
    url(r'^history/$', views.transaction_history_view, name='transaction_history')

]

tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from tutorial import views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('', views.home_view, name='home-view'),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls', namespace='accounts')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        <br>
        <div class="container">
            <nav class="navbar navbar-default">
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">BANK</a>
              </div>
              <div id="navbar" class="navbar-collapse collapse">
                {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:overview_profile' %}">Overview</a></li>
                    <li><a href="{% url 'accounts:view_profile' %}">Profile</a></li>
                    <li><a href="{% url 'accounts:edit_profile' %}">Edit Profile</a></li>
                    <li><a href="{% url 'accounts:change_password' %}">Change Password</a></li>
                    {% if user.is_superuser %} <li><a href="/admin/">ADMIN</a></li> {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
                </ul>
                {% else %}
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'accounts:reset_password' %}">Reset Password</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  <li><a href="{% url 'accounts:register' %}">Register</a></li>
                </ul>
                {% endif %}
              </div><!--/.nav-collapse -->
            </div><!--/.container-fluid -->
          </nav>
        </div>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
    <script
      src="https://code.jquery.com/jquery-3.1.1.min.js"
      integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
      crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>

templates/home.html
{% extends 'base.html' %}

{% block head %}
<title>Home Page</title>
{% endblock %}


{% block body %}
<div class="container">
    <br>

<h1><p><span id="time"></span></p></h1>


<script>
var dt = new Date();
document.getElementById("date").innerHTML = (("0"+dt.getDate()).slice(-2)) +"."+ (("0"+(dt.getMonth()+1)).slice(-2)) +"."+ (dt.getFullYear());
</script>
<script>
var dt = new Date();
document.getElementById("time").innerHTML = (("0"+dt.getHours()).slice(-2)) +":"+ (("0"+dt.getMinutes()).slice(-2));
</script>
</div>


<div class="container">
<h3><p>{{ source }} /   {{ date }}</p></h3>
    <table class="centerTable" align="left" style="margin: 0px auto;">
      <thead>
        <tr>
            <th width="100"><p>Currency</p></th>
            <th width="100"><p>to RON</p></th>
        </tr>
      </thead>
      <tbody>
        <tr>
        {% for rate in rates %}
          <td>{{ rate.currency }}</td>
          <td> {{ rate.rate }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>

{% endblock %}

templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}